#pragma once

#define LOWER_HVC_TEST_PING 1
#define LOWER_HVC_TEST_PASS 2
#define LOWER_HVC_TEST_FAIL 3

#define LOWER_HVC_TEST_ARG_MAGIC 42
#define LOWER_HVC_TEST_RETURN_MAGIC 0x6767
#define LOWER_HVC_TEST_PING_IMM 0x77
